"""Migração inicial - tabelas do sistema de carteirinhas

Revision ID: 024ec9e42b13
Revises: 5f7958945e30
Create Date: 2025-06-29 19:45:26.123633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024ec9e42b13'
down_revision = '5f7958945e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email_administracao', sa.String(length=120), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('horario_funcionamento', sa.String(length=100), nullable=True),
    sa.Column('logo_filename', sa.String(length=100), nullable=True),
    sa.Column('cor_primaria', sa.String(length=7), nullable=True),
    sa.Column('cor_secundaria', sa.String(length=7), nullable=True),
    sa.Column('dias_aviso_vencimento', sa.Integer(), nullable=True),
    sa.Column('meses_validade_padrao', sa.Integer(), nullable=True),
    sa.Column('permitir_dependentes', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('salva_vidas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salva_vidas_id'], ['salva_vidas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('tabela', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('data_acao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_auditoria')
    op.drop_table('usuarios')
    op.drop_table('configuracao_sistema')
    op.drop_table('condominio')
    # ### end Alembic commands ###
