"""Migração inicial - tabelas do sistema de carteirinhas

Revision ID: 5f7958945e30
Revises: 
Create Date: 2025-06-29 18:38:18.391196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7958945e30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('bloco', sa.String(length=10), nullable=False),
    sa.Column('apartamento', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('eh_titular', sa.Boolean(), nullable=False),
    sa.Column('email_titular', sa.String(length=120), nullable=True),
    sa.Column('data_ultima_validacao', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('carteirinha_ativa', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('notificacao_30_dias_enviada', sa.Boolean(), nullable=True),
    sa.Column('notificacao_vencimento_enviada', sa.Boolean(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anexos_moradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('morador_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('tamanho_arquivo', sa.Integer(), nullable=False),
    sa.Column('tipo_arquivo', sa.String(length=50), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['morador_id'], ['moradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('morador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_notificacao', sa.String(length=50), nullable=False),
    sa.Column('email_enviado', sa.String(length=120), nullable=False),
    sa.Column('status_envio', sa.String(length=20), nullable=False),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['morador_id'], ['moradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_notificacoes')
    op.drop_table('anexos_moradores')
    op.drop_table('moradores')
    # ### end Alembic commands ###
