"""Criar tabela visitantes

Revision ID: a1b2c3d4e5f6
Revises: 54fe7b36cfb8
Create Date: 2025-11-04 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '54fe7b36cfb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=True),
    sa.Column('veiculo_modelo', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('morador_id', sa.Integer(), nullable=False),
    sa.Column('apartamento_destino', sa.String(length=10), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=False),
    sa.Column('data_saida_prevista', sa.DateTime(), nullable=True),
    sa.Column('data_saida_real', sa.DateTime(), nullable=True),
    sa.Column('autorizado_por', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('entrada_autorizada', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autorizado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['morador_id'], ['moradores.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitantes')
    # ### end Alembic commands ###

