"""Criar tabelas de reservas de espaços

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2025-11-04 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar tabela espacos_comuns
    op.create_table('espacos_comuns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=True),
    sa.Column('area_metros', sa.Numeric(10, 2), nullable=True),
    sa.Column('tempo_antecipacao_horas', sa.Integer(), nullable=True),
    sa.Column('tempo_maximo_horas', sa.Integer(), nullable=True),
    sa.Column('valor_taxa', sa.Numeric(10, 2), nullable=True),
    sa.Column('requer_aprovacao', sa.Boolean(), nullable=True),
    sa.Column('horario_inicio', sa.Time(), nullable=True),
    sa.Column('horario_fim', sa.Time(), nullable=True),
    sa.Column('dias_semana_disponiveis', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('fotos', sa.JSON(), nullable=True),
    sa.Column('equipamentos', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Criar tabela reservas_espacos
    op.create_table('reservas_espacos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('espaco_id', sa.Integer(), nullable=False),
    sa.Column('morador_id', sa.Integer(), nullable=False),
    sa.Column('data_reserva', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('quantidade_pessoas', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('aprovado_por', sa.Integer(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('motivo_recusa', sa.Text(), nullable=True),
    sa.Column('finalidade', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('taxa_paga', sa.Boolean(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(10, 2), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['espaco_id'], ['espacos_comuns.id'], ),
    sa.ForeignKeyConstraint(['morador_id'], ['moradores.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    
    # Criar tabela lista_convidados
    op.create_table('lista_convidados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.Column('data_entrada', sa.DateTime(), nullable=True),
    sa.Column('data_saida', sa.DateTime(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas_espacos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lista_convidados')
    op.drop_table('reservas_espacos')
    op.drop_table('espacos_comuns')
    # ### end Alembic commands ###

