"""Adicionar relacionamento condominio_id na tabela moradores

Revision ID: c22ad5b7299f
Revises: 024ec9e42b13
Create Date: 2025-06-29 19:56:23.670840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22ad5b7299f'
down_revision = '024ec9e42b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condominio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_morador_condominio', 'condominio', ['condominio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moradores', schema=None) as batch_op:
        batch_op.drop_constraint('fk_morador_condominio', type_='foreignkey')
        batch_op.drop_column('condominio_id')

    # ### end Alembic commands ###
